services:
  backend:
    build:
      context: ./backendpheonix
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:4000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./vue-front
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:8080"

volumes:
  db_data:
